import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import ProfilePic from "../../public/images/profile/sebby.png"
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
            <div className='w-1/2'>
              <Image src={ProfilePic} alt="Sebby" className='w-full h-auto' />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <h1></h1>
              <AnimatedText text="Turning vision into reality with code and design." className='!text-5xl !text-left'/>
              <p className='my-4 text-base font-medium'>My name is <em className='underline'>Sebby</em>. I am freelance creative developer, 3D Animator and graphics designer.
                My goal is to combine creative thinking and design with an analytical approach to solve problems at the intersection of business and technology. 
                Feel free to drop me a line,
                Cheers : )
              </p>
              <div className='flex items-center self-start mt-2'>
                <Link href="/dummy.pdf" target={'_blank'} className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark' download={true}>
                  Resume <LinkArrow className={"w-6 ml-1"}/>
                </Link>
                <Link href="mailto:sebbyapudo@gmail.com" target={'-blank'} 
                className='ml-4 text-lg font-medium capitalize text-dark underline'
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
